[server]
#网络线程个数
net-threads     = 3

[HelloObjAdapter]
#监听IP地址
endpoint =tcp -h  127.0.0.1 -p 19388 -t 60000
#允许的IP地址
allow       =
#最大连接数
maxconns    = 1024
#当前线程个数
threads     = 5
#流量限制
queuecap    = 10000
#队列超时时间
queuetimeout= 60000
#处理对象
servant     = FF.HelloServer.HelloObj
protocol=taf